// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVSNrtNEmclI0jtMEvHWt4QrCdZDDCB0',
    appId: '1:937666435898:web:9afd33bac3b0b64e69ce03',
    messagingSenderId: '937666435898',
    projectId: 'eds-app-1758d',
    authDomain: 'eds-app-1758d.firebaseapp.com',
    storageBucket: 'eds-app-1758d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALw-U0pYlfgrRjPE47knbmJtsY8Kd2xA',
    appId: '1:937666435898:ios:e995c5c9afa164ce69ce03',
    messagingSenderId: '937666435898',
    projectId: 'eds-app-1758d',
    storageBucket: 'eds-app-1758d.firebasestorage.app',
    androidClientId: '937666435898-mqbe3htqj2d3vfkuo96usm16h70kbg04.apps.googleusercontent.com',
    iosClientId: '937666435898-7kn2f8bkhkhq4k9n9lmdp2g8o9birhs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.edsApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1gcyoMxhlLe-lMSbWXLWoEX1di9DYZY',
    appId: '1:937666435898:android:ba01066b47f5eae069ce03',
    messagingSenderId: '937666435898',
    projectId: 'eds-app-1758d',
    storageBucket: 'eds-app-1758d.firebasestorage.app',
  );

}